a = input('Digite algo: ')
print('O tipo primitivo desse valor é {}'.format(type(a)))
print('Só tem espaços? {}'.format(a.isnumeric()))
print('É um número? {}'.format(a.isnumeric()))
print('É alfabético? {}'.format(a.isalpha()))
print('É alfanumérico? {}'.format(a.isalnum()))
print('Está em maiúscuças? {}'.format(a.isupper()))
print('Está em minúsculas? {}'.format(a.islower()))
